### ISSUE TITLE
Problem with space sign in SSID

### ISSUE THREAD

**Issue by JoergSH** [jonask1337/esp-idf-nat-example#10]

**Comment by JoergSH** [comment]
Hello I have a Acces Point with a fixed SSID with Space Signs in it ( Deeper CHRIP+ 7798).
Any Idea to make that work.

**Comment by jonask1337** [comment]
Hi, to my knowledge connecting with the ESP32 to an access point with spaces in its SSID is not a problem. I tested it by setting the access point of an ESP32 to the SSID "Deeper CHRIP+ 7798"
and then connected to it with another ESP32.

**Comment by jonask1337** [comment]
Closed this issue due to inactivity. Please reopen if the issue still exists.
