### ISSUE TITLE
post a binary?

### ISSUE THREAD

**Issue by mahesh2000** [jonask1337/esp-idf-nat-example#8]
hi, i've had trouble installing the idf. would you post a binary? that would be most helpful. thanks.

**Comment by jonask1337** [comment]
Hi, I do not think that the binary for this example would be helpful to you. The binary would not have the right configuration for the network the esp32 should connect to. This must be set before the project is build.
What problems do you have with installing the esp-idf?

**Comment by mahesh2000** [comment]
@martin-ger posted an [esp nat router](https://github.com/martin-ger/esp32_nat_router) binary last week, it works quite well.
